package com.projectatlas.quest

import org.bukkit.entity.Player
import java.util.UUID

/**
 * Represents a quest defined in code.
 * Designed to be easily generated by AI or written manually.
 */
interface CodeableQuest {
    val id: String
    val name: String
    val description: String
    
    fun canStart(player: Player): Boolean
    fun onStart(player: Player)
    fun onComplete(player: Player)
}

/**
 * Manages active quests and the registry of available quests.
 */
object AgentQuestManager {
    private val quests = mutableMapOf<String, CodeableQuest>()
    private val activeQuests = mutableMapOf<UUID, MutableSet<String>>()

    fun registerQuest(quest: CodeableQuest) {
        quests[quest.id] = quest
    }

    fun getQuest(id: String): CodeableQuest? = quests[id]

    fun startQuest(player: Player, questId: String): Boolean {
        val quest = quests[questId] ?: return false
        if (!quest.canStart(player)) return false
        
        activeQuests.computeIfAbsent(player.uniqueId) { mutableSetOf() }.add(questId)
        quest.onStart(player)
        return true
    }

    fun completeQuest(player: Player, questId: String) {
        // Logic to complete
        if (activeQuests[player.uniqueId]?.contains(questId) == true) {
            val quest = quests[questId]
            quest?.onComplete(player)
            activeQuests[player.uniqueId]?.remove(questId)
        }
    }
    
    fun isQuestActive(player: Player, questId: String): Boolean {
         return activeQuests[player.uniqueId]?.contains(questId) == true
    }
}
