name: ProjectAtlas
version: '${version}'
main: com.projectatlas.AtlasPlugin
api-version: '1.21'
authors: [Antigravity]
description: A multiplayer-first RPG systems plugin.
softdepend: [Typewriter]
commands:
  atlas:
    description: Main command for Project Atlas
    usage: /atlas <subcommand>
  pc:
    description: Party chat
    usage: /pc <message>
    aliases: [partychat]
  agentquest:
    description: Manage Agent/Codeable quests
    usage: /agentquest start <id>
permissions:
  atlas.admin:
    description: Allows administrative control over Atlas systems
    default: op
  atlas.player:
    description: Default player permissions
    default: true
  atlas.mayor:
    description: Permissions for mayors
    default: true
